#######
# Compiled from data/sumo/functions/load.mcscript
# to .//data/sumo/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
compiler!
scoreboard objectives add w-firework dummy
scoreboard objectives add w-firework-id dummy
scoreboard objectives add w-firework-id-test dummy
scoreboard objectives add w-firework-order dummy

# Extended from sumo/functions/firework/mount.mcscript
# to data/sumo/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add w-firework-flight dummy
scoreboard objectives add w-firework-owner-0 dummy
scoreboard objectives add w-firework-owner-1 dummy
scoreboard objectives add w-firework-owner-2 dummy
scoreboard objectives add w-firework-owner-3 dummy
scoreboard objectives add w-firework-uuid-0 dummy
scoreboard objectives add w-firework-uuid-1 dummy
scoreboard objectives add w-firework-uuid-2 dummy
scoreboard objectives add w-firework-uuid-3 dummy
scoreboard objectives add w-firework-success dummy

# Extended from data/sumo/functions/load.mcscript
# to data/sumo/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add w-world dummy
scoreboard objectives add w-stick dummy

# Extended from sumo/functions/shop/!shop.mcscript
# to data/sumo/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add w-currency-sugar dummy
scoreboard objectives add w-currency-pearl dummy
