#######
# Compiled from data/sumo/functions/load.mcscript
# to .//data/sumo/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
y the compiler!
scoreboard objectives add w-firework dummy

# Extended from data/sumo/functions/load.mcscript
# to data/sumo/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add w-world dummy
scoreboard objectives add w-stick dummy

# Extended from sumo/functions/shop/!shop.mcscript
# to data/sumo/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add w-currency-sugar dummy
scoreboard objectives add w-currency-pearl dummy
