#######
# Compiled from sumo/functions/fire_charge/fire_charge.mcscript
# to .//data/sumo/functions/fire_charge/fire_charge.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:fireball] run scoreboard players remove @s w-fire-charge 1
execute as @e[type=minecraft:fireball] if score @s w-fire-charge matches ..-1 run kill @s