#######
# Compiled from sumo/functions/world/set_world_center.mcscript
# to .//data/sumo/functions/world/set_world_center.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store result storage w:world center[0] double 1 run data get entity @s Pos[0]
execute store result storage w:world center[1] double 1 run data get entity @s Pos[2]
function sumo:world/update_center
function sumo:world/update_border