#######
# Compiled from sumo/functions/world/set_world_spawn.mcscript
# to .//data/sumo/functions/world/set_world_spawn.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[tag=w-world-spawn] at @s if block ~ ~ ~ air run tp ~ ~-1 ~
execute as @e[tag=w-world-spawn] at @s if block ~ ~ ~ air run function sumo:world/set_world_spawn
execute as @e[tag=w-world-spawn] at @s unless block ~ ~ ~ air run setworldspawn ~ ~1 ~
execute as @e[tag=w-world-spawn] at @s unless block ~ ~ ~ air run kill @s