#######
# Compiled from sumo/functions/world/update_center.mcscript
# to .//data/sumo/functions/world/update_center.mcfunction
#
# Generated by Minecraft Script for 1.16
######
kill @e[tag=w-worldCenter]
summon minecraft:snowball ~ -65 ~ {NoGravity:1b,Tags:["w-worldCenter"]}
execute as @e[tag=w-worldCenter] store result entity @s Pos[0] double 1 run data get storage w:world center[0]
execute as @e[tag=w-worldCenter] store result entity @s Pos[2] double 1 run data get storage w:world center[1]
execute as @e[tag=w-worldCenter] at @s run worldborder center ~ ~