#######
# Compiled from sumo/functions/world/update_border_recursive.mcscript
# to ./sumo/data/sumo/functions/world/update_border_recursive.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players remove border w-world 1
worldborder add 1
execute if score border w-world matches 2.. run function sumo:world/update_border_recursive
