#######
# Compiled from sumo/functions/kill/kill.mcscript
# to .//data/sumo/functions/kill/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a at @s if entity @s[y=-30,dy=60] unless block ~ ~-0.1 ~ minecraft:air run function sumo:kill/use_totem
execute as @a at @s if entity @s[y=-30,dy=60] unless block ~ ~-0.1 ~ minecraft:air if entity @s[nbt={Health:0f}] run tellraw @a [{"selector":"@s","color":"blue","bold":true},{"text":" fazla derindeydi.","color":"blue","bold":false}]
execute as @a at @s if block ~ ~0.1 ~ minecraft:water run function sumo:kill/use_totem
execute as @a at @s if block ~ ~0.1 ~ minecraft:water if entity @s[nbt={Health:0f}] run tellraw @a [{"selector":"@s","color":"blue","bold":true},{"text":" boğuldu!","color":"blue","bold":false}]
execute as @a at @s if block ~ ~0.1 ~ minecraft:lava run function sumo:kill/use_totem
execute as @a at @s if block ~ ~0.1 ~ minecraft:lava if entity @s[nbt={Health:0f}] run tellraw @a [{"selector":"@s","color":"blue","bold":true},{"text":" lavda yüzmeye çalıştı.","color":"blue","bold":false}]
execute as @e[type=!minecraft:player] at @s if block ~ ~0.1 ~ minecraft:water run kill @s
execute as @e[type=!minecraft:player] at @s if entity @s[y=-63,dy=93] run kill @s