#######
# Compiled from sumo/functions/kill/kill.mcscript
# to ./sumo/data/sumo/functions/kill/kill.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a at @s if entity @s[y=0,dy=30] run function sumo:kill/use_totem
execute as @a at @s if entity @s[y=0,dy=30] if entity @s[nbt={Health:0f}] run tellraw @a [{"selector":"@s","color":"blue","bold":true},{"text":" fazla derindeydi.","color":"blue","bold":false}]
execute as @a at @s if block ~ ~0.1 ~ minecraft:water run function sumo:kill/use_totem
execute as @a at @s if block ~ ~0.1 ~ minecraft:water if entity @s[nbt={Health:0f}] run tellraw @s [{"selector":"@s","color":"blue","bold":true},{"text":" boğuldu!","color":"blue","bold":false}]