#######
# Compiled from sumo/functions/kill/spread_player.mcscript
# to .//data/sumo/functions/kill/spread_player.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute at @e[tag=w-worldCenter] run spreadplayers ~ ~ 1 80 false @s