#######
# Compiled from sumo/functions/kill/use_totem.mcscript
# to .//data/sumo/functions/kill/use_totem.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute unless entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run kill @s
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run tellraw @a [{"selector":"@s","color":"yellow","bold":true},{"text":" totem kulllanarak hayatta kaldı.","bold":false}]
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run setblock ~ 255 ~ minecraft:barrel
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run item replace block ~ 255 ~ container.0 from entity @s weapon.offhand
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run item replace entity @s weapon.offhand with minecraft:totem_of_undying
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run damage @s 1000000
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run item replace entity @s weapon.offhand from block ~ 255 ~ container.0
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run setblock ~ 255 ~ minecraft:air
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run function sumo:kill/spread_player
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] at @s run playsound minecraft:item.totem.use player @a ~ ~ ~
execute if entity @s[nbt={Inventory:[{id:"minecraft:dirt",tag:{w-totem:1b}}]}] run clear @s minecraft:dirt{w-totem:1b} 1