#######
# Compiled from sumo/functions/kill/use_totem.mcscript
# to .//data/sumo/functions/kill/use_totem.mcfunction
#
# Generated by Minecraft Script for 1.16
######
data get entity @s Inventory[{Slot:-106b,id:"minecraft:totem_of_undying"}]
execute unless entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run kill @s[nbt=!{Inventory:[{id:"minecraft:totem_of_undying"}]}]
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run tellraw @a [{"selector":"@s","color":"yellow","bold":true},{"text":" totem kulllanarak hayatta kaldı.","bold":false}]
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run setblock ~ 255 ~ minecraft:barrel
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run item replace block ~ 255 ~ container.0 from entity @s weapon.offhand
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run item replace entity @s weapon.offhand with minecraft:totem_of_undying
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run damage @s 1000000
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run item replace entity @s weapon.offhand from block ~ 255 ~ container.0
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run setblock ~ 255 ~ minecraft:air
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run function sumo:kill/spread_player
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] at @s run playsound minecraft:item.totem.use player @s
execute if entity @s[nbt={Inventory:[{id:"minecraft:totem_of_undying"}]}] run clear @s minecraft:totem_of_undying 1