#######
# Compiled from sumo/functions/items/firework2.mcscript
# to .//data/sumo/functions/items/firework2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
schedule function sumo:items/firework2 12s
execute at @e[tag=w-worldCenter] as @a run summon minecraft:item ~ ~1 ~ {Tags:["w-age","w-spread"],Item:{id:"minecraft:firework_rocket",Count:1b,tag:{display:{Name:'[{"text":"Bin","italic":false,"color":"red","bold":true}]'},w-rideable:1b,w-effect:1b,Enchantments:[{}],Fireworks:{Flight:3},CanPlaceOn:["minecraft:sand","minecraft:gravel","minecraft:grass_block","minecraft:grass","minecraft:stone"],HideFlags:16}}}