#######
# Compiled from sumo/functions/items/fire_charge.mcscript
# to .//data/sumo/functions/items/fire_charge.mcfunction
#
# Generated by Minecraft Script for 1.16
######
schedule function sumo:items/fire_charge 10s replace
execute at @e[tag=w-worldCenter] as @a run summon minecraft:item ~ ~ ~ {Tags:["w-age","w-spread"],Item:{id:"minecraft:ender_eye",Count:1b,tag:{CustomModelData:2,display:{Name:'[{"text":"Bum","italic":false,"color":"red","bold":true}]'},w-fire-charge:1b}}}