#######
# Compiled from sumo/functions/items/firework2.mcscript
# to .//data/sumo/functions/items/firework2.mcfunction
#
# Generated by Minecraft Script for 1.16
######
schedule function sumo:items/firework2 30s replace
execute at @e[tag=w-worldCenter] as @a run summon minecraft:item ~ ~ ~ {Tags:["w-age","w-spread"],Item:{id:"minecraft:ender_eye",Count:1b,tag:{CustomModelData:1,display:{Name:'[{"text":"Bin","italic":false,"color":"red","bold":true}]'},w-enchanted:1b,Enchantments:[{}],w-firework:1b}}}