#######
# Compiled from sumo/functions/items/firework1.mcscript
# to .//data/sumo/functions/items/firework1.mcfunction
#
# Generated by Minecraft Script for 1.16
######
schedule function sumo:items/firework1 20s
execute at @e[tag=w-worldCenter] as @a run summon minecraft:item ~ ~1 ~ {Tags:["w-age","w-spread"],Item:{id:"minecraft:ender_eye",Count:1b,tag:{CustomModelData:1,display:{Name:'[{"text":"Bin","italic":false,"color":"red","bold":true}]'},w-rideable:1b,w-firework:1b}}}