#######
# Compiled from sumo/functions/items/!items.mcscript
# to .//data/sumo/functions/items/items.mcfunction
#
# Generated by Minecraft Script for 1.16
######
schedule clear sumo:items/firework1
function sumo:items/firework1
schedule clear sumo:items/firework2
function sumo:items/firework2
schedule clear sumo:items/snowball
function sumo:items/snowball
schedule clear sumo:items/sugar
function sumo:items/sugar
schedule clear sumo:items/ender_pearl
function sumo:items/ender_pearl