#######
# Compiled from sumo/functions/items/!items.mcscript
# to .//data/sumo/functions/items/items.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function sumo:items/firework1
function sumo:items/firework2
function sumo:items/snowball
function sumo:items/sugar
function sumo:items/ender_pearl
function sumo:items/fire_charge