#######
# Compiled from sumo/functions/items/snowball.mcscript
# to .//data/sumo/functions/items/snowball.mcfunction
#
# Generated by Minecraft Script for 1.16
######
schedule function sumo:items/snowball 7s
execute at @e[tag=w-worldCenter] as @a run summon minecraft:item ~ ~1 ~ {Tags:["w-age","w-spread"],Item:{id:"minecraft:snowball",Count:1b,tag:{display:{Name:'[{"text":"Zıp","italic":false,"color":"red","bold":true}]'},w-bouncing:1b}}}