#######
# Compiled from sumo/functions/firework/control.mcscript
# to .//data/sumo/functions/firework/control.mcfunction
#
# Generated by Minecraft Script for 1.16
######




scoreboard players operation @a w-firework-id-test = @s w-firework-id
tag @s add w-firework
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test run tag @s add w-firework-owner
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test as @e[tag=w-firework] at @s store result entity @s Rotation[0] int 1 run data get entity @a[tag=w-firework-owner,limit=1] Rotation[0] 1
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test as @e[tag=w-firework] at @s store result entity @s Rotation[1] int 1 run data get entity @a[tag=w-firework-owner,limit=1] Rotation[1] 1
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test run summon minecraft:snowball ^ ^ ^2 {Tags:["w-firework-entity"]}
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test store result score x1 w-firework run data get entity @s Pos[0] 1000
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test store result score y1 w-firework run data get entity @s Pos[1] 1000
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test store result score z1 w-firework run data get entity @s Pos[2] 1000
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test as @e[tag=w-firework-entity] store result score x2 w-firework run data get entity @s Pos[0] 1000
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test as @e[tag=w-firework-entity] store result score y2 w-firework run data get entity @s Pos[1] 1000
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test as @e[tag=w-firework-entity] store result score z2 w-firework run data get entity @s Pos[2] 1000
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test as @e[tag=w-firework-entity] run kill @s
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test run scoreboard players operation x2 w-firework -= x1 w-firework
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test run scoreboard players operation y2 w-firework -= y1 w-firework
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test run scoreboard players operation z2 w-firework -= z1 w-firework
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test store result entity @e[tag=w-firework,limit=1] Motion[0] double 0.0005 run scoreboard players get x2 w-firework 
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test store result entity @e[tag=w-firework,limit=1] Motion[1] double 0.0005 run scoreboard players get y2 w-firework 
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test store result entity @e[tag=w-firework,limit=1] Motion[2] double 0.0005 run scoreboard players get z2 w-firework 
execute as @a at @s if score @s w-firework-id = @s w-firework-id-test run tag @s remove w-firework-owner
tag @s remove w-firework