#######
# Compiled from sumo/functions/firework/firework.mcscript
# to .//data/sumo/functions/firework/firework.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tag @e[type=minecraft:firework_rocket,nbt={FireworksItem:{tag:{w-rideable:1b}}},tag=!w-mounted,limit=1] add w-firework
execute as @e[limit=1,tag=w-firework] run function sumo:firework/mount
execute as @e[type=minecraft:firework_rocket,tag=w-mounted] at @s run function sumo:firework/control