#######
# Compiled from sumo/functions/firework/!firework.mcscript
# to .//data/sumo/functions/firework/firework.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @e[type=minecraft:firework_rocket,tag=w-mounted] at @s run function sumo:firework/control