#######
# Compiled from sumo/functions/firework/order.mcscript
# to .//data/sumo/functions/firework/order.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players operation @s w-firework-order = w-firework-order w-firework-order
scoreboard players add w-firework-order w-firework-order 1