#######
# Compiled from sumo/functions/firework/summon.mcscript
# to .//data/sumo/functions/firework/summon.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tag @e[type=minecraft:eye_of_ender,nbt={Item:{tag:{w-firework:1b}}}] add w-ender-eye
execute if score @s w-ender-eye matches 1.. store result score @s w-firework-enchanted run data get entity @e[limit=1,tag=w-ender-eye] Item.tag.w-enchanted
execute if score @s w-ender-eye matches 1.. run function sumo:firework/mount
execute if score @s w-ender-eye matches 1.. run scoreboard players set @s w-ender-eye 0

kill @e[tag=w-ender-eye]