#######
# Compiled from data/sumo/functions/bouncing_snowball.mcscript
# to ./sumo/data/sumo/functions/bouncing_snowball.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tag @e[type=minecraft:snowball,nbt={Item:{tag:{w-bouncing:1b}}},limit=1] add w-snowball
execute as @e[tag=w-snowball,limit=1] at @s run effect give @e[distance=0..5] minecraft:levitation 1 5 true
execute as @e[tag=w-snowball,limit=1] run tag @s remove w-snowball