#######
# Compiled from data/sumo/functions/entity_hurt_player.mcscript
# to .//data/sumo/functions/entity_hurt_player.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only sumo:entity_hurt_player
ride @s dismount