#######
# Compiled from data/sumo/functions/give_items.mcscript
# to .//data/sumo/functions/give_items.mcfunction
#
# Generated by Minecraft Script for 1.16
######
item replace entity @a container.0 with minecraft:stick{display:{Name:'[{"text":"Fetiş Çubuğu","italic":false,"color":"red","bold":true}]'},Enchantments:[{id:knockback,lvl:4}],AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:100,Slot:mainhand,Operation:2,Name:"generic.attack_speed",UUID:[I;-121726,6411,153256,-12822]}],HideFlags:39,w-stick:1b}
item replace entity @a container.1 with minecraft:bow{Unbreakable:1,display:{Name:'[{"text":"Fetiş Yayı","italic":false,"color":"red","bold":true}]'},Enchantments:[{id:punch,lvl:3}],HideFlags:37,w-stick:1b}
item replace entity @a container.35 with minecraft:arrow{display:{Name:'[{"text":"Ok","italic":false,"color":"red","bold":true}]'},w-stick:1b}