#######
# Compiled from data/sumo/functions/used_ender_eye.mcscript
# to .//data/sumo/functions/used_ender_eye.mcfunction
#
# Generated by Minecraft Script for 1.16
######
advancement revoke @s only sumo:used_ender_eye
execute if entity @e[type=minecraft:eye_of_ender,nbt={Item:{tag:{w-firework:1b}}}] run function sumo:firework/summon
