#######
# Compiled from data/sumo/functions/using_item.mcscript
# to .//data/sumo/functions/using_item.mcfunction
#
# Generated by Minecraft Script for 1.16
######
say 1
advancement revoke @s only sumo:using_item
execute if entity @e[type=minecraft:egg,nbt={Item:{tag:{w-fire-charge:1b}}}] run function sumo:fire_charge/summon
