#######
# Compiled from functions/shop/signs/invisibility_20.mcscript
# to .//data/sumo/functions/shop/signs/invisibility_20.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s dark_oak_sign{display:{Name:'{"text":"Görünmezlik 20s","italic":false}'},BlockEntityTag:{front_text:{messages:['{"text":"20s","color":"dark_aqua"}','{"text":"Görünmezlik","color":"aqua","bold":true,"clickEvent":{"action":"run_command","value":"/function sumo:shop/buy/invisibility_20"}}','{"text":"16 Şeker","color":"dark_aqua","italic":true}','{"text":""}']}}} 1