#######
# Compiled from functions/shop/signs/jump_ii_40.mcscript
# to .//data/sumo/functions/shop/signs/jump_ii_40.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s dark_oak_sign{display:{Name:'{"text":"Zıplama II 40s","italic":false}'},BlockEntityTag:{front_text:{messages:['{"text":"II 40s","color":"dark_aqua"}','{"text":"Zıplama İksiri","color":"aqua","bold":true,"clickEvent":{"action":"run_command","value":"/function sumo:shop/buy/jump_ii_40"}}','{"text":"3 Şeker","color":"dark_aqua","italic":true}','{"text":""}']}}} 1