#######
# Compiled from functions/shop/signs/jump_iv_20.mcscript
# to .//data/sumo/functions/shop/signs/jump_iv_20.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s dark_oak_sign{display:{Name:'{"text":"Zıplama IV 20s","italic":false}'},BlockEntityTag:{front_text:{messages:['{"text":"IV 20s","color":"dark_aqua"}','{"text":"Zıplama İksiri","color":"aqua","bold":true,"clickEvent":{"action":"run_command","value":"/function sumo:shop/buy/jump_iv_20"}}','{"text":"2 Şeker","color":"dark_aqua","italic":true}','{"text":""}']}}} 1