#######
# Compiled from functions/shop/signs/speed_i_20.mcscript
# to .//data/sumo/functions/shop/signs/speed_i_20.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s dark_oak_sign{display:{Name:'{"text":"Hız I 20s","italic":false}'},BlockEntityTag:{front_text:{messages:['{"text":"I 20s","color":"dark_aqua"}','{"text":"Hız İksiri","color":"aqua","bold":true,"clickEvent":{"action":"run_command","value":"/function sumo:shop/buy/speed_i_20"}}','{"text":"2 Şeker","color":"dark_aqua","italic":true}','{"text":""}']}}} 1