#######
# Compiled from functions/shop/signs/totem.mcscript
# to .//data/sumo/functions/shop/signs/totem.mcfunction
#
# Generated by Minecraft Script for 1.16
######
give @s dark_oak_sign{display:{Name:'{"text":"Totem","italic":false}'},BlockEntityTag:{front_text:{messages:['{"text":""}','{"text":"Totem","color":"aqua","bold":true,"clickEvent":{"action":"run_command","value":"/function sumo:shop/buy/totem"}}','{"text":"5 Göz","color":"dark_aqua","italic":true}','{"text":""}']}}} 1