#######
# Compiled from sumo/functions/shop/!calculate_currency.mcscript
# to .//data/sumo/functions/shop/calculate_currency.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute store result score @s w-currency-sugar run clear @s minecraft:sugar{w-shop:1b} 0
execute store result score @s w-currency-pearl run clear @s minecraft:ender_pearl{w-shop:1b} 0