#######
# Compiled from sumo/functions/shop/jump_iv_40.mcscript
# to ./sumo/data/sumo/functions/shop/jump_iv_40.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function sumo:shop/calculate_currency
execute if score @s w-currency-sugar matches 6.. run give @p splash_potion{CustomPotionColor:16448655,display:{Name:'[{"text":"Zıplama İksiri","italic":false,"bold":true,"color":"red"}]'},CustomPotionEffects:[{Id:8,Duration:800,Amplifier:3}]} 1
execute if score @s w-currency-sugar matches 6.. run clear @s sugar{w-shop:1b} 6
