#######
# Compiled from sumo/functions/shop/!shop.mcscript
# to .//data/sumo/functions/shop/shop.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard objectives add w-currency-sugar dummy
scoreboard objectives add w-currency-pearl dummy

