#######
# Compiled from sumo/functions/shop/speed_i_20.mcscript
# to ./sumo/data/sumo/functions/shop/speed_i_20.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function sumo:shop/calculate_currency
execute if score @s w-currency-sugar matches 2.. run give @p splash_potion{CustomPotionColor:3336444,display:{Name:'[{"text":"Hız İksiri","italic":false,"bold":true,"color":"red"}]'},CustomPotionEffects:[{Id:1,Duration:400}]} 1
execute if score @s w-currency-sugar matches 2.. run clear @s sugar{w-shop:1b} 2
