#######
# Compiled from sumo/functions/shop/totem.mcscript
# to ./sumo/data/sumo/functions/shop/totem.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function sumo:shop/calculate_currency
execute if score @s w-currency-pearl matches 3.. run give @p totem_of_undying{display:{Name:'[{"text":"Ölümsüzlük Totemi","italic":false,"color":"red","bold":true}]'}} 1
execute if score @s w-currency-pearl matches 3.. run clear @s ender_pearl{w-shop:1b} 3
